// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BlackFox.Stidgen.Tests")>]
[<assembly: AssemblyProductAttribute("stidgen")>]
[<assembly: AssemblyDescriptionAttribute("Strongly Typed ID type Generator")>]
[<assembly: AssemblyVersionAttribute("1.1")>]
[<assembly: AssemblyFileVersionAttribute("1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BlackFox.Stidgen.Tests"
    let [<Literal>] AssemblyProduct = "stidgen"
    let [<Literal>] AssemblyDescription = "Strongly Typed ID type Generator"
    let [<Literal>] AssemblyVersion = "1.1"
    let [<Literal>] AssemblyFileVersion = "1.1"
