// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BlackFox.Stidgen")>]
[<assembly: AssemblyProductAttribute("stidgen")>]
[<assembly: AssemblyDescriptionAttribute("Strongly Typed ID type Generator")>]
[<assembly: AssemblyVersionAttribute("0.5.4")>]
[<assembly: AssemblyFileVersionAttribute("0.5.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BlackFox.Stidgen"
    let [<Literal>] AssemblyProduct = "stidgen"
    let [<Literal>] AssemblyDescription = "Strongly Typed ID type Generator"
    let [<Literal>] AssemblyVersion = "0.5.4"
    let [<Literal>] AssemblyFileVersion = "0.5.4"
